---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-works
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    steps:
      - attach_workspace:
          at: ~/
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-works
      - run:
          name: Wait for Solr
          command: dockerize -wait tcp://localhost:8985 -timeout 1m
      - run:
          name: Load config into Solr
          command: |
            cd "$(bundle show active-fedora)/lib/generators/active_fedora/config/solr/templates/solr/config"
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8985/solr/admin/configs?action=UPLOAD&name=solrconfig"
            curl -H 'Content-type: application/json' http://localhost:8985/api/collections/ -d '{create: {name: hydra-test, config: solrconfig, numShards: 1}}'
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - bundle:
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - test:
          name: "ruby2-5-5"
          ruby_version: "2.5.5"
          requires:
            - bundle
      - test:
          name: "ruby2-6-2"
          ruby_version: "2.6.2"
          requires:
            - bundle
